version: '3.3'
services:
  mariadb:
    image: mariadb:10
    container_name: 'todo_db'
    restart: always
    ports:
      - "5306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ : Asia/Seoul